#!/bin/bash -e

case ${1} in

    configure)
        service nginx restart
        service uwsgi restart || true
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst no reconoce el argumento '"${1}"'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0