#!/bin/bash -e

case ${1} in

    install|upgrade)
        #Si el servicio de apache esta activo lo detenemos para poner correr el server de django
        if [ -e /var/lib/dpkg/info/apache2.list ] || [ -e /var/lib/live/config/apache2 ]; then
            service apache2 stop
        fi

        service nginx stop

        mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bk
    ;;

    abort-upgrade|abort-install)

    ;;

    *)
        echo "preinst no reconoce el argumento '"${1}"'" >&2
        exit 1
    ;;

esac

#DEBHELPER#

exit 0